# Jako Data Frame

Preprocesing obecně
* https://www.analyticsvidhya.com/blog/2016/07/practical-guide-data-preprocessing-python-scikit-learn/

Zdroje:

* https://stackoverflow.com/questions/34170413/possible-ways-to-do-one-hot-encoding-in-scikit-learn

## Přes pandas

Zdroj je [zde](https://stackoverflow.com/questions/34170413/possible-ways-to-do-one-hot-encoding-in-scikit-learn)

Plusy:
* Asi z toho dostanu dobře konverzi pro nové přes názvy sloupců.

Mínusy:
* Sparsity není.

In [3]:
import pandas as pd

In [4]:
train_df = pd.DataFrame(
    data=[[1,2,3.01,10], [2,3,4.02,20], [3,4,5.03,30]],
    columns=["Jedna", "Dva", "Tri", "Ctyri"]
)
dtypes = {"Jedna": "category", "Dva": "category", "Tri": "f8", "Ctyri":"int8"}

for c in train_df.columns:
    train_df[c] = train_df[c].astype(dtypes[c])

for c in train_df.columns:    
    print (train_df[c].dtype )  #=> int64

category
category
float64
int8


In [5]:
train_df

Jedna Dva   Tri  Ctyri
0     1   2  3.01     10
1     2   3  4.02     20
2     3   4  5.03     30

In [6]:
df_dumm = pd.get_dummies(train_df)
df_dumm

Tri  Ctyri  Jedna_1  Jedna_2  Jedna_3  Dva_2  Dva_3  Dva_4
0  3.01     10        1        0        0      1      0      0
1  4.02     20        0        1        0      0      1      0
2  5.03     30        0        0        1      0      0      1

In [7]:
a = df_dumm.columns
type(a)

pandas.indexes.base.Index

In [8]:
a

Index(['Tri', 'Ctyri', 'Jedna_1', 'Jedna_2', 'Jedna_3', 'Dva_2', 'Dva_3',
       'Dva_4'],
      dtype='object')

In [9]:
"Tri" in a

True

In [10]:
#PRO ZVOLENÝ SLOUPEC
pd.get_dummies(train_df, columns=["Ctyri"]).head()

Jedna Dva   Tri  Ctyri_10  Ctyri_20  Ctyri_30
0     1   2  3.01         1         0         0
1     2   3  4.02         0         1         0
2     3   4  5.03         0         0         1

## SK learn

[OneHotEncoder](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [9]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [3]:
train_df = pd.DataFrame(
    data=[[1,2,3.01,10], [2,3,4.02,20], [3,4,5.03,30]],
    columns=["Jedna", "Dva", "Tri", "Ctyri"]
)
dtypes = {"Jedna": "category", "Dva": "category", "Tri": "f8", "Ctyri":"int8"}

for c in train_df.columns:
    train_df[c] = train_df[c].astype(dtypes[c])

for c in train_df.columns:    
    print (train_df[c].dtype )  #=> int64

category
category
float64
int8


In [13]:
one_hot = preprocessing.OneHotEncoder(
    categorical_features=[0,1,3],
    sparse=False, 
    handle_unknown="ignore"
)
df_dumm_sk = one_hot.fit_transform(train_df)
print(type(df_dumm_sk))
print(df_dumm_sk)

<class 'numpy.ndarray'>
[[ 1.    0.    0.    1.    0.    0.    1.    0.    0.    3.01]
 [ 0.    1.    0.    0.    1.    0.    0.    1.    0.    4.02]
 [ 0.    0.    1.    0.    0.    1.    0.    0.    1.    5.03]]


In [5]:
one_hot.get_params

<bound method BaseEstimator.get_params of OneHotEncoder(categorical_features=[0, 1, 3], dtype=<class 'numpy.float64'>,
       handle_unknown='ignore', n_values='auto', sparse=False)>

In [6]:
one_hot.transform([train_df.iloc[0]])

array([[ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,
         3.01]])

In [10]:
#one_hot.transform([4,2,5.43,10])
one_hot.transform(np.reshape([4,2,5.43,10], (1,-1)))

array([[ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,
         5.43]])

In [11]:
one_hot.transform(np.reshape([40,20,5.43,100], (1,-1)))

array([[ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         5.43]])

In [12]:
type(train_df)

pandas.core.frame.DataFrame

In [16]:
type([40,20,5.43,100]) == list

True