# Jako Data Frame

Preprocesing obec+
* https://www.analyticsvidhya.com/blog/2016/07/practical-guide-data-preprocessing-python-scikit-learn/

Zdroje:

* https://stackoverflow.com/questions/34170413/possible-ways-to-do-one-hot-encoding-in-scikit-learn

## Přes pandas

Zdroj je [zde](https://stackoverflow.com/questions/34170413/possible-ways-to-do-one-hot-encoding-in-scikit-learn)

Plusy:
* Asi z toho dostanu dobře konverzi pro nové přes názvy sloupců.

Mínusy:
* Sparsity není.

In [30]:
import pandas as pd

In [50]:
train_df = pd.DataFrame(
    data=[[1,2,3.01,10], [2,3,4.02,20], [3,4,5.03,30]],
    columns=["Jedna", "Dva", "Tri", "Ctyri"]
)
dtypes = {"Jedna": "category", "Dva": "category", "Tri": "f8", "Ctyri":"int8"}

for c in train_df.columns:
    train_df[c] = train_df[c].astype(dtypes[c])

for c in train_df.columns:    
    print (train_df[c].dtype )  #=> int64

category
category
float64
int8


In [51]:
train_df

Jedna Dva   Tri  Ctyri
0     1   2  3.01     10
1     2   3  4.02     20
2     3   4  5.03     30

In [52]:
df_dumm = pd.get_dummies(train_df)
df_dumm

Tri  Ctyri  Jedna_1  Jedna_2  Jedna_3  Dva_2  Dva_3  Dva_4
0  3.01     10        1        0        0      1      0      0
1  4.02     20        0        1        0      0      1      0
2  5.03     30        0        0        1      0      0      1

In [53]:
a = df_dumm.columns
type(a)

pandas.indexes.base.Index

In [54]:
a

Index(['Tri', 'Ctyri', 'Jedna_1', 'Jedna_2', 'Jedna_3', 'Dva_2', 'Dva_3',
       'Dva_4'],
      dtype='object')

In [55]:
"Tri" in a

True

In [56]:
#PRO ZVOLENÝ SLOUPEC
pd.get_dummies(train_df, columns=["Ctyri"]).head()

Jedna Dva   Tri  Ctyri_10  Ctyri_20  Ctyri_30
0     1   2  3.01         1         0         0
1     2   3  4.02         0         1         0
2     3   4  5.03         0         0         1

## SK learn

In [57]:
from sklearn import preprocessing

In [60]:
one_hot = preprocessing.OneHotEncoder(sparse = False, categorical_features=[0,1,3])
df_dumm_sk = one_hot.fit_transform(train_df)
print(df_dumm_sk)

[[ 1.    0.    0.    1.    0.    0.    1.    0.    0.    3.01]
 [ 0.    1.    0.    0.    1.    0.    0.    1.    0.    4.02]
 [ 0.    0.    1.    0.    0.    1.    0.    0.    1.    5.03]]


In [61]:
one_hot.get_params

<bound method BaseEstimator.get_params of OneHotEncoder(categorical_features=[0, 1, 3], dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=False)>

In [64]:
one_hot.transform([train_df.iloc[0]])

array([[ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,
         3.01]])

In [65]:
one_hot.transform([4,2,5.43,10])

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: unknown categorical feature present [4] during transform.