# Standardizace

In [4]:
import pandas as pd
import numpy as np

## Normalizace - pandas

* Tady to nějak moc nefunguje. Překvapuje mě, že na to není easy operace.

In [5]:
train_df = pd.DataFrame(
    data=[[1,2,3.0,10], [2,3,4.0,20], [3,4,5.0,30]],
    columns=["Jedna", "Dva", "Tri", "Ctyri"]
)
dtypes = {"Jedna": "category", "Dva": "category", "Tri": "f8", "Ctyri":"int8"}

for c in train_df.columns:
    train_df[c] = train_df[c].astype(dtypes[c])

#for c in train_df.columns:    
#    print (train_df[c].dtype )  #=> int64
train_df

Jedna Dva  Tri  Ctyri
0     1   2  3.0     10
1     2   3  4.0     20
2     3   4  5.0     30

In [4]:
train_df.mean()

Jedna     2.0
Dva       3.0
Tri       4.0
Ctyri    20.0
dtype: float64

In [5]:
train_df.std()

Jedna     1.0
Dva       1.0
Tri       1.0
Ctyri    10.0
dtype: float64

In [15]:
#[train_df - train_df.mean()

In [10]:
#(train_df - train_df.mean())/train_df.std()

In [12]:
#train_df_norm = (train_df - train_df.mean()) / (train_df.max() - train_df.min())
#train_df_norm

## Přes sklearn

[Preprocessing](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html)

* Tohle je fajn - jsem schopen si uložit tu transformaci zvlášť.

preprocessing.scale()
* normalizuje, ale neuchová transformaci.

preprocessing.StandardScaler()
* Uchová transformaci

In [1]:
from sklearn import preprocessing

In [25]:
train_df = pd.DataFrame(
    data=[[1,2,3.0,10,1], [2,3,4.0,20,0], [3,4,5.0,30,0]],
    columns=["Jedna", "Dva", "Tri", "Ctyri", "Pet"]
)
train_df

Jedna  Dva  Tri  Ctyri  Pet
0      1    2  3.0     10    1
1      2    3  4.0     20    0
2      3    4  5.0     30    0

In [26]:
#this is just a scaler
norm_data = preprocessing.scale(train_df)
print(norm_data)
print(norm_data.mean(axis=0))
print(norm_data.std(axis=0))

[[-1.22474487 -1.22474487 -1.22474487 -1.22474487  1.41421356]
 [ 0.          0.          0.          0.         -0.70710678]
 [ 1.22474487  1.22474487  1.22474487  1.22474487 -0.70710678]]
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   7.40148683e-17]
[ 1.  1.  1.  1.  1.]


#### Jako transformace

In [30]:
scaler = preprocessing.StandardScaler().fit(train_df)
print(scaler.mean_)
print(scaler.scale_)

[  2.   3.   4.  20.]
[ 0.81649658  0.81649658  0.81649658  8.16496581]


In [31]:
norm_data = scaler.transform(train_df)
print(norm_data)
print(norm_data.mean(axis=0))
print(norm_data.std(axis=0))

[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]
[ 0.  0.  0.  0.]
[ 1.  1.  1.  1.]


In [32]:
scaler.transform([[2,3,4,40]])

array([[ 0.        ,  0.        ,  0.        ,  2.44948974]])

#### Jako transformace postupně.

In [34]:
# set
scaler = preprocessing.StandardScaler(
    with_mean=False,
    with_std=True
)

In [35]:
# fit
scaler.fit_transform(train_df)

array([[ 1.22474487,  2.44948974,  3.67423461,  1.22474487,  2.12132034],
       [ 2.44948974,  3.67423461,  4.89897949,  2.44948974,  0.        ],
       [ 3.67423461,  4.89897949,  6.12372436,  3.67423461,  0.        ]])

In [36]:
# tr
scaler.transform(np.reshape([1.0,1.0,1.0,1.0, 1], (1, -1)))

array([[ 1.22474487,  1.22474487,  1.22474487,  0.12247449,  2.12132034]])

In [51]:
print(scaler.mean_)
print(scaler.var_)
print(scaler.scale_)

[  2.           3.           4.          20.           0.33333333]
[  0.66666667   0.66666667   0.66666667  66.66666667   0.22222222]
[ 0.81649658  0.81649658  0.81649658  8.16496581  0.47140452]


In [47]:
print(np.mean([1,2,3]))
print(np.std([1,2,3]))

2.0
0.816496580928


In [53]:
mu = np.mean([1,2,3])
std = np.std([1,2,3])
([1, 2, 3] - mu)/np.std([1,2,3])

array([-1.22474487,  0.        ,  1.22474487])

In [54]:
print(([1, 2, 3])/np.std([1,2,3]))
print(([1, 2, 3])/np.std([1,2,3]) - mu/std)

[ 1.22474487  2.44948974  3.67423461]
[-1.22474487  0.          1.22474487]


#### ŘÍDKÉ MATICE
dát tam with_mean=False, aby se nenarušila sparsity